export const PET_COLORS: Record<string, string> = {
    'B': '#105051', // Dark outline / legs / arms
    'M': '#69b09f', // Main body green/teal
    'A': '#8dcabe', // Lighter body highlight
    'S': '#d9f1cd', // Screen background
    'E': '#12413f', // Eyes / mouth
    'Y': '#facc15', // Yellow D-Pad
    'D': '#1e3a8a', // Dark blue button
    'R': '#e11d48', // Red button
    'G': '#86efac', // Green button
    'L': '#38bdf8', // Light blue button
    'W': '#4b9087', // Shadow under screen

    // Props colors
    'P': '#f472b6', // Pink balloon
    'O': '#38bdf8', // Water drops / watering can
    'C': '#60a5fa', // Sleep Zzzs
};

export const COFFEE_COLORS: Record<string, string> = {
    'W': '#f8fafc', // Body white
    'A': '#0d9488', // Teal arms/legs
    'B': '#475569', // Outline (changed from dark to slate for dark mode visibility)
    'I': '#334155', // Inner mug dark
    'C': '#9f1239', // Coffee splash (reddish)
    'S': '#cbd5e1', // Shadow
};

// --- MUG2: Classic Coffee Mug v2 (24x24 grid) ---
// Layout: left wall col 5, interior cols 6-17 (12px), right wall col 18, handle cols 19-22
// Left arm: cols 1-4, right arm: cols 19-22 (below handle), legs: cols 8-9 & 13-14
export const MUG2_COLORS: Record<string, string> = {
    'W': '#f0f4f8', // Cool white ceramic
    'B': '#334155', // Slate outline (clear in both themes)
    'A': '#0d9488', // Teal arms/legs
    'C': '#7c3f00', // Coffee dark brown
    'E': '#1e293b', // Eyes
    'S': '#fda4af', // Blush dots
    'H': '#e2e8f0', // Handle interior highlight
};

export const MUG2_FRAMES: Record<string, string[]> = {
    idle: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    blink: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    look_left: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BEEWWWWWWWWEEWB   B ",
        "     BEEWWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    look_right: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEEB   B ",
        "     BWEEWWWWWWWEEEB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    happy: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWESSWWWWSSESWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWEEEEEEWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "          AA  AA        ",
        "         AAA  AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    walk1: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWBAAAA ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "      AA        AA      ",
        "     AAA         AAA    ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    walk2: [
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWBAAAA ",
        "     BBBBBBBBBBBBBBB    ",
        "      AA                ",
        "      AA          AA    ",
        "     AAA         AAA    ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    walk3: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWBAAAA ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "         AAA  AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    walk4: [
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "  AAABWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWBAAAA ",
        "     BBBBBBBBBBBBBBB    ",
        "                  AA    ",
        "     AA           AA    ",
        "     AAA         AAA    ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    inflate1: [
        "          CCC           ",
        "         CCCCC          ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    inflate2: [
        "         CCCCC          ",
        "        CCCCCCC         ",
        "       CC     CC        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA    AAA       ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
    ],
    water1: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA  C AA        ",
        "       AAA  C AAA       ",
        "            C           ",
        "                        ",
        "                        ",
        "                        ",
    ],
    water2: [
        "                        ",
        "                        ",
        "                        ",
        "      BBBBBBBBBBBB      ",
        "     BCCCCCCCCCCCCB     ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWEEWWWWWWWEEWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWEEWWEEWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWB   B ",
        "     BWWWWWWWWWWWWBBBBB ",
        "     BWWWWWWWWWWWWB     ",
        "     BBBBBBBBBBBBBBB    ",
        "                        ",
        "        AA    AA        ",
        "       AAA  C AAA       ",
        "           CCC          ",
        "                        ",
        "                        ",
        "                        ",
    ],
};

export const PET_FRAMES: Record<string, string[]> = {
    idle: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    blink: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSSSSSSSSSSB  ",
        "  BSSSSSSSSSSB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    look_left: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BEEESSSSEESB  ",
        "  BEEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    look_right: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEEEB  ",
        "  BSEESSSSEEEB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    walk1: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "   B       B    ",
        "  BB        BB  "
    ],
    walk2: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "    B           ",
        "    B       BB  ",
        "   BB      BB   "
    ],
    walk3: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "      BB BB     "
    ],
    walk4: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "           B    ",
        "   BB      B    ",
        "  BB      BB    "
    ],
    happy: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSESSSSSSESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "      B  B      ",
        "     BB  BB     "
    ],
    inflate1: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESPPPEESB  ",
        "  BSSSPPPPPSSB  ",
        "  BMMMPPPWMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    inflate2: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSPPPPSSSB  ",
        "  BSEPPPPPPESB  ",
        "  BSEPPPPPPESB  ",
        "  BSSPPPPPPSSB  ",
        "  BMMMPPPPMMMB  ",
        "  BBWMMMMMMDMBBB",
        "  BBMYMMMMMLMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMMMMB  ",
        "    BBBBBBBBB   ",
        "     B    B     ",
        "    BBB  BBB    "
    ],
    water1: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSEESSSSEESB  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMM DMBB ",
        "  BBMYMMMM LMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMMMM M B ",
        "    BBBBBBB M B ",
        "     B    B MMB ",
        "    BBB  BBB    "
    ],
    water2: [
        "                ",
        "                ",
        "   BBBBBBBBBB   ",
        "  BMMMMMMMMMMB  ",
        "  BSSSSSSSSSSB  ",
        "  BSSEESSSSEES  ",
        "  BSEESSSSEESB  ",
        "  BSSSSSSSSSSB  ",
        "  BMMMMWWMMMMB  ",
        "  BBWMMMMM DMBB ",
        "  BBMYMMMM LMB B",
        "  B BMMMMMRGMB B",
        "   BMMMMM MB MB ",
        "    BBBBB BMB B ",
        "     B    B O B ",
        "    BBB  BB B O "
    ],
};

export const COFFEE_FRAMES: Record<string, string[]> = {
    idle: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWW B ",
        "  BWWBBWWBBWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    blink: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWWWWWWWWW B ",
        "  BWWWWWWWWWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    look_left: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BBWWBBWWWWW B ",
        "  BBWWBBWWWWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    look_right: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWWWBBWWBB B ",
        "  BWWWWBBWWBB B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    walk1: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWW B ",
        "  BWWBBWWBBWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "   A        A   ",
        "  AAA        AAA",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    walk2: [
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWW B ",
        "  BWWBBWWBBWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "    A           ",
        "    A       AA  ",
        "   AAA     AAA  ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    walk3: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWW B ",
        "  BWWBBWWBBWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "     A    A     ",
        "      AAA  AAA  ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    walk4: [
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWW B ",
        "  BWWBBWWBBWW B ",
        " ABWWWWWWWWWW BB",
        "AABWWWWWWWWWWBAA",
        "  BBBBBBBBBBBB  ",
        "           A    ",
        "   AA      A    ",
        "  AAA     AAA   ",
        "                ",
        "                ",
        "                ",
        "                "
    ],
    happy: [
        "      CCC       ",
        "     CCCCC      ",
        "    CCIIIIC     ",
        "  BCCCCIIIICCB  ",
        "  BCWWWWWWWWCCB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWWB B",
        "  BWWBBWWBBWWB B",
        " ABWWWWWWWWWW AB",
        "AABWWWWWWWWWWBB A",
        "  BBBBBBBBBBBB  ",
        "   AAA    AAA   ",
        "    A      A    ",
        "                ",
        "                ",
        "                "
    ],
    inflate1: [ // Used for coffee idle task (blowing steam)
        "       S        ",
        "      SSS       ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWWB B",
        "  BWWBBWWBBWWB B",
        " ABWWWWWWWWWW AB",
        "AABWWWWWWWWWWBB A",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                "
    ],
    inflate2: [
        "      SSS       ",
        "     SSSSS      ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWWB B",
        "  BWWBBWWBBWWB B",
        " ABWWWWWWWWWW AB",
        "AABWWWWWWWWWWBB A",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA    AAA   ",
        "                ",
        "                ",
        "                "
    ],
    water1: [ // coffee spilling
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWWB B",
        "  BWWBBWWBBWWB B",
        " ABWWWWWWWWWW AB",
        "AABWWWWWWWWWWBB A",
        "  BBBBBBBBBBBB  ",
        "    A    C A    ",
        "   AAA   CAAA   ",
        "         C      ",
        "                ",
        "                ",
        "                "
    ],
    water2: [
        "                ",
        "   BBBBBBBBBB   ",
        "  BIIIIIIIIIIB  ",
        "  BWWWWWWWWWWBB ",
        "  BWWWWWWWWWW WB",
        "  BWWBBWWBBWWB B",
        "  BWWBBWWBBWWB B",
        " ABWWWWWWWWWW AB",
        "AABWWWWWWWWWWBB A",
        "  BBBBBBBBBBBB  ",
        "    A      A    ",
        "   AAA  C AAA   ",
        "       CCC      ",
        "                ",
        "                ",
        "                "
    ]
};
